use_frameworks!

target 'LZLogining_Example' do
  pod 'LZLogining', :path => '../'
  pod 'LZNetworking', :path => '../../LZNetworking'

  target 'LZLogining_Tests' do
    inherit! :search_paths

    
  end
end
